import { useState } from 'react'
import { BellRing, Check, ClipboardCheck, Clock, Database, Download, FileCheck2, Fingerprint, LockKeyhole, Radar, School, ShieldCheck, UserCheck, Users } from 'lucide-react'

const problems=[['Informasi terlambat','Orang tua sering baru mengetahui ketidakhadiran setelah kegiatan sekolah selesai.',Clock],['Data tidak selalu tepercaya','Pencatatan manual dan praktik titip absen dapat mengurangi integritas data.',Fingerprint],['Administrasi berulang','Guru dan operator harus mengolah informasi yang sama berkali-kali untuk kebutuhan laporan.',ClipboardCheck]]
const steps=[['Kehadiran tercatat langsung','Guru dan siswa melakukan absensi dalam sistem yang sama, lengkap dengan waktu dan validasi lokasi.',UserCheck],['Data diperiksa','Identitas, waktu, lokasi, dan histori aktivitas membantu menjaga keakuratan data.',ShieldCheck],['Orang tua mengetahui lebih cepat','Ketidakhadiran dapat diberitahukan secara real-time tanpa menunggu rekap akhir hari.',BellRing,'Dalam pengembangan'],['Sekolah menindaklanjuti','Wali kelas dan pimpinan sekolah melihat informasi yang membutuhkan perhatian.',Radar],['Laporan siap digunakan','Data kehadiran tersusun untuk kebutuhan operasional dan pelaporan sekolah.',FileCheck2]]
const pillars=[['Terhubung','Guru, wali kelas, orang tua, operator, dan pimpinan sekolah bekerja menggunakan informasi yang sama.',Users],['Tepercaya','Waktu, lokasi, identitas, dan histori perubahan membantu menjaga integritas data kehadiran.',ShieldCheck],['Proaktif','Pola ketidakhadiran dan keterlambatan menjadi sinyal agar sekolah dapat menindaklanjuti lebih awal.',Radar],['Siap digunakan','Data tidak berhenti di dashboard, tetapi disiapkan untuk laporan dan kebutuhan operasional.',Database]]
const roles={'Kepala Sekolah':'Pantau kondisi sekolah hari ini tanpa menunggu laporan manual.','Guru':'Absen sendiri dan mencatat kehadiran siswa dari dashboard kelas yang sama.','Wali Kelas':'Lihat siswa yang terlambat, sering izin, atau membutuhkan tindak lanjut.','Operator':'Unduh rekap yang sudah tersusun tanpa mengolah ulang data dari awal.','Orang Tua':'Dapatkan informasi kehadiran dan kirim keterangan izin atau sakit dengan lebih cepat.'}
const security=['Validasi lokasi dan waktu','Pencegahan titip absen','Role dan permission','Approval bertahap','Audit trail','Pemisahan data antar sekolah']
const exports=['Rekap H/I/S/A dan persentase kehadiran','Data pendukung e-Rapor','Rekap absensi guru untuk DHGTK','Data pendukung BOS dan PIP','Laporan untuk kepala sekolah dan yayasan','Export Excel standar']
const roadmap=[['Fondasi utama','Tersedia',['Absensi guru dan siswa','Data kelas dan warga sekolah','Role dan permission','Dashboard operasional','Kedisiplinan dasar']],['Tahap berikutnya','Dalam pengembangan',['Notifikasi WhatsApp','Pengajuan izin digital','Early warning','Export laporan sekolah','Kanal pelaporan aman','Gamifikasi kehadiran']],['Visi ekosistem','Visi jangka panjang',['SPP dan keuangan','PPDB','Catatan perkembangan siswa','Kolaborasi wali kelas dan orang tua']]]
function Title({eyebrow,title,desc,dark=false}){return <div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-brand-600 dark:text-brand-200">{eyebrow}</p><h2 className={`mt-4 text-3xl font-bold tracking-[-.03em] sm:text-4xl ${dark?'text-white':'text-slate-950 dark:text-white'}`}>{title}</h2>{desc&&<p className={`mt-4 max-w-2xl leading-7 ${dark?'text-slate-300':'text-slate-600 dark:text-slate-300'}`}>{desc}</p>}</div>}

export default function LandingSections(){const[role,setRole]=useState('Kepala Sekolah');const moveTab=(event)=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const tabs=[...event.currentTarget.parentElement.querySelectorAll('[role="tab"]')];const current=tabs.indexOf(event.currentTarget);const next=event.key==='Home'?0:event.key==='End'?tabs.length-1:(current+(event.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[next].focus();tabs[next].click()};return <>
<section id="solusi" className="landing-section bg-white py-24 dark:bg-slate-950"><div className="landing-wrap"><Title eyebrow="Masalah yang diselesaikan" title="Absensi seharusnya tidak berhenti pada rekap." desc="Ketika data hanya dikumpulkan, sekolah tetap terlambat mengetahui masalah. Gakuren menghubungkan pencatatan, pemberitahuan, tindak lanjut, dan pelaporan dalam satu alur."/><div className="mt-12 grid gap-4 md:grid-cols-3">{problems.map(([t,d,I])=><article key={t} className="landing-card"><I className="text-brand-600"/><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
<section id="cara-kerja" className="landing-section bg-slate-50 py-24 dark:bg-slate-900"><div className="landing-wrap"><Title eyebrow="Cara kerja" title="Dari kehadiran menjadi tindakan."/><ol className="mt-12 grid gap-4 lg:grid-cols-5">{steps.map(([t,d,I,s],i)=><li key={t} className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-950"><span className="text-xs font-bold text-brand-700 dark:text-brand-200">0{i+1}</span><I className="mt-5 text-brand-600"/><h3 className="mt-4 font-bold dark:text-white">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{d}</p>{s&&<span className="status-label">{s}</span>}</li>)}</ol></div></section>
<section className="landing-section bg-white py-24 dark:bg-slate-950"><div className="landing-wrap"><Title eyebrow="Nilai Gakuren" title="Satu sistem. Empat nilai utama."/><div className="mt-12 grid gap-4 md:grid-cols-2">{pillars.map(([t,d,I])=><article key={t} className="landing-card"><I className="text-brand-600"/><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
<section id="dampak" className="landing-section bg-slate-50 py-24 dark:bg-slate-900"><div className="landing-wrap"><Title eyebrow="Dampak" title="Informasi yang tepat untuk setiap peran."/><div className="mt-10 rounded-2xl border border-slate-200 bg-white p-3 dark:border-slate-700 dark:bg-slate-950"><div role="tablist" aria-label="Peran pengguna" className="flex gap-2 overflow-x-auto p-1">{Object.keys(roles).map(r=><button key={r} id={`tab-${r}`} role="tab" aria-selected={role===r} aria-controls="role-panel" tabIndex={role===r?0:-1} onKeyDown={moveTab} onClick={()=>setRole(r)} className={`whitespace-nowrap rounded-full px-4 py-2.5 text-sm font-semibold ${role===r?'bg-brand-600 text-white':'text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800'}`}>{r}</button>)}</div><div id="role-panel" role="tabpanel" aria-labelledby={`tab-${role}`} tabIndex="0" className="m-1 mt-4 rounded-xl bg-brand-50 p-7 text-lg font-semibold leading-8 text-slate-900 dark:bg-slate-900 dark:text-white"><School className="mb-4 text-brand-600"/>{roles[role]}</div></div></div></section>
<section className="landing-section bg-[#07111f] py-24 text-white"><div className="landing-wrap grid gap-12 lg:grid-cols-[1fr_.8fr] lg:items-center"><Title dark eyebrow="Sinyal awal" title={<>Satu ketidakhadiran adalah data.<br/>Pola yang berulang adalah sebuah sinyal.</>} desc="Gakuren membantu sekolah mengenali perubahan pola kehadiran, keterlambatan, dan kedisiplinan agar wali kelas dapat bertindak lebih awal."/><article className="rounded-2xl border border-white/15 bg-white/[.06] p-6"><span className="status-label">Dalam pengembangan</span><p className="mt-5 text-sm font-semibold text-amber-300">Perlu perhatian</p><h3 className="mt-2 text-xl font-bold">Siti Nurhaliza</h3><ul className="mt-4 space-y-2 text-sm text-slate-300"><li>3 kali izin mendadak dalam 14 hari</li><li>2 kali terlambat pada hari Senin</li></ul><div className="mt-5 border-t border-white/10 pt-4"><p className="text-xs text-slate-400">Rekomendasi</p><p className="mt-1 font-semibold">Tinjau bersama wali kelas</p></div></article></div></section>
<section id="keamanan" className="landing-section bg-white py-24 dark:bg-slate-950"><div className="landing-wrap grid gap-12 lg:grid-cols-[1fr_.8fr]"><Title eyebrow="Keamanan dan integritas" title="Keputusan yang baik dimulai dari data yang dapat dipercaya." desc="Validasi lokasi, identitas perangkat, histori perubahan, role-based access, dan approval bertahap membantu sekolah menjaga keakuratan serta akuntabilitas data."/><ul className="grid gap-3 sm:grid-cols-2">{security.map(x=><li key={x} className="flex items-center gap-3 rounded-xl border border-slate-200 p-4 text-sm font-semibold dark:border-slate-700 dark:text-white"><LockKeyhole size={18} className="text-brand-600"/>{x}</li>)}</ul></div></section>
<section className="landing-section bg-slate-50 py-24 dark:bg-slate-900"><div className="landing-wrap"><Title eyebrow="Export dan administrasi" title="Data yang siap digunakan, bukan sekadar disimpan." desc="Gakuren membantu operator menyiapkan rekap kehadiran untuk kebutuhan sekolah tanpa mengolah ulang data dari awal."/><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{exports.map(x=><div key={x} className="flex gap-3 rounded-xl bg-white p-4 text-sm font-medium dark:bg-slate-950 dark:text-white"><Download size={18} className="shrink-0 text-brand-600"/>{x}</div>)}</div><p className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-900 dark:border-amber-900 dark:bg-amber-950/40 dark:text-amber-100">Gakuren menyiapkan file untuk digunakan operator. Data tidak dikirim langsung ke Dapodik tanpa mekanisme dan izin resmi.</p></div></section>
<section id="roadmap" className="landing-section bg-white py-24 dark:bg-slate-950"><div className="landing-wrap"><Title eyebrow="Roadmap" title={<>Dimulai dari kehadiran.<br/>Berkembang bersama kebutuhan sekolah.</>}/><div className="mt-12 grid gap-5 lg:grid-cols-3">{roadmap.map(([t,s,items])=><article key={t} className="landing-card"><span className="status-label">{s}</span><h3 className="mt-5">{t}</h3><ul className="mt-5 space-y-3">{items.map(x=><li key={x} className="flex gap-2 text-sm text-slate-600 dark:text-slate-300"><Check size={17} className="shrink-0 text-brand-600"/>{x}</li>)}</ul></article>)}</div></div></section>
</>}
