import { useState } from 'react'
import { BellRing, ClipboardCheck, Clock, Database, FileCheck2, Fingerprint, History, LockKeyhole, MapPin, Radar, School, ShieldCheck, UserCheck, Users } from 'lucide-react'

const problems=[['Informasi terlambat','Orang tua baru mengetahui ketidakhadiran setelah kegiatan sekolah selesai.',Clock],['Data tidak selalu tepercaya','Pencatatan manual dapat mengurangi integritas data.',Fingerprint],['Administrasi berulang','Informasi yang sama harus diolah berkali-kali untuk laporan.',ClipboardCheck]]
const steps=[['Kehadiran tercatat','Waktu, identitas, dan lokasi disimpan.',UserCheck],['Data diverifikasi','Informasi diperiksa untuk menjaga integritas.',ShieldCheck],['Orang tua diberi tahu','Ketidakhadiran dapat diketahui lebih cepat.',BellRing],['Sekolah menindaklanjuti','Wali kelas melihat hal yang membutuhkan perhatian.',Radar],['Laporan tersedia','Data tersusun untuk kebutuhan operator.',FileCheck2]]
const roles={'Kepala Sekolah':'Pantau kondisi sekolah hari ini tanpa menunggu laporan manual.','Guru':'Absen dan catat kehadiran siswa dari dashboard kelas yang sama.','Wali Kelas':'Lihat siswa yang terlambat, sering izin, atau perlu ditinjau.','Operator':'Siapkan rekap tersusun tanpa mengolah ulang data dari awal.','Orang Tua':'Terima informasi kehadiran dan kirim keterangan lebih cepat.'}
const security=['Validasi lokasi dan waktu','Identitas perangkat','Role dan permission','Approval bertahap','Audit trail','Pemisahan data antar sekolah']
const reports=[['Kehadiran',['Rekap H/I/S/A','Persentase kehadiran','Rekap absensi guru']],['Akademik',['Data pendukung e-Rapor','Rekap kelas']],['Administrasi',['Data pendukung BOS dan PIP','Laporan kepala sekolah dan yayasan','Export Excel']]]

function Title({eyebrow,title,desc,dark=false}){return <div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-brand-600 dark:text-brand-200">{eyebrow}</p><h2 className={`mt-4 text-3xl font-bold tracking-[-.03em] sm:text-4xl ${dark?'text-white':'text-slate-950 dark:text-white'}`}>{title}</h2>{desc&&<p className={`mt-4 max-w-2xl leading-7 ${dark?'text-slate-300':'text-slate-600 dark:text-slate-300'}`}>{desc}</p>}</div>}

export default function LandingSections(){
  const[role,setRole]=useState('Kepala Sekolah')
  const moveTab=(event)=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const tabs=[...event.currentTarget.parentElement.querySelectorAll('[role="tab"]')];const current=tabs.indexOf(event.currentTarget);const next=event.key==='Home'?0:event.key==='End'?tabs.length-1:(current+(event.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[next].focus();tabs[next].click()}
  return <>
    <section id="solusi" className="landing-section bg-white py-24 dark:bg-slate-950"><div className="landing-wrap"><Title eyebrow="Masalah yang diselesaikan" title="Absensi seharusnya tidak berhenti pada rekap." desc="Gakuren menghubungkan pencatatan, pemberitahuan, tindak lanjut, dan pelaporan dalam satu alur."/><div className="mt-10 grid gap-4 md:grid-cols-3">{problems.map(([t,d,I])=><article key={t} className="landing-card"><I size={22} className="text-brand-600"/><h3 className="!mt-4">{t}</h3><p>{d}</p></article>)}</div></div></section>
    <section id="cara-kerja" className="landing-section bg-slate-50 py-24 dark:bg-slate-900"><div className="landing-wrap"><Title eyebrow="Cara kerja" title="Dari kehadiran menjadi tindakan."/><ol className="relative mt-10 grid gap-0 lg:grid-cols-5 lg:gap-4">{steps.map(([t,d,I],i)=><li key={t} className="relative grid grid-cols-[48px_1fr] gap-3 pb-7 last:pb-0 lg:block lg:pb-0"><div className="relative z-10 grid h-11 w-11 place-items-center rounded-full bg-brand-600 text-xs font-bold text-white">0{i+1}</div>{i<steps.length-1&&<span aria-hidden="true" className="absolute left-[21px] top-11 h-[calc(100%-44px)] w-px bg-brand-200 lg:left-11 lg:top-[21px] lg:h-px lg:w-[calc(100%-28px)]"/>}<div className="pt-1 lg:pt-0"><I size={20} className="hidden text-brand-600 lg:mt-5 lg:block"/><h3 className="font-bold text-slate-950 dark:text-white lg:mt-4">{t}</h3><p className="mt-1 text-sm leading-6 text-slate-600 dark:text-slate-300">{d}</p></div></li>)}</ol></div></section>
    <section className="landing-section bg-white py-24 dark:bg-slate-950"><div className="landing-wrap"><Title eyebrow="Nilai Gakuren" title="Satu sistem. Empat nilai utama."/><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3"><article className="overflow-hidden rounded-3xl bg-[#07111f] p-6 text-white md:col-span-2 lg:row-span-2"><div className="flex items-center gap-3"><ShieldCheck className="text-brand-200"/><h3 className="text-xl font-bold">Tepercaya</h3></div><p className="mt-3 max-w-xl text-sm leading-6 text-slate-300">Waktu, lokasi, identitas, dan histori perubahan menjaga konteks setiap catatan kehadiran.</p><div className="mt-7 rounded-2xl border border-white/10 bg-white/[.06] p-4"><div className="flex items-center justify-between text-sm"><span>Riwayat verifikasi</span><span className="text-emerald-300">Terverifikasi</span></div><div className="mt-4 grid gap-3 text-xs text-slate-300 sm:grid-cols-3"><span className="flex gap-2"><MapPin size={15}/>Lokasi sesuai</span><span className="flex gap-2"><Fingerprint size={15}/>Perangkat dikenal</span><span className="flex gap-2"><History size={15}/>Jejak tersimpan</span></div></div></article>{[['Terhubung','Informasi yang sama untuk seluruh peran.',Users],['Proaktif','Pola menjadi sinyal untuk ditinjau lebih awal.',Radar],['Siap Digunakan','Data disiapkan untuk laporan operasional.',Database]].map(([t,d,I])=><article key={t} className="landing-card"><div className="flex items-center gap-3"><I size={20} className="text-brand-600"/><h3 className="!mt-0">{t}</h3></div><p>{d}</p></article>)}</div></div></section>
    <section id="dampak" className="landing-section bg-slate-50 py-24 dark:bg-slate-900"><div className="landing-wrap"><Title eyebrow="Dampak" title="Informasi yang tepat untuk setiap peran."/><div className="mt-10 rounded-2xl border border-slate-200 bg-white p-3 dark:border-slate-700 dark:bg-slate-950"><div role="tablist" aria-label="Peran pengguna" className="landing-tabs flex gap-2 overflow-x-auto p-1 pb-2">{Object.keys(roles).map(r=><button key={r} id={`tab-${r.replaceAll(' ','-')}`} role="tab" aria-selected={role===r} aria-controls="role-panel" tabIndex={role===r?0:-1} onKeyDown={moveTab} onClick={()=>setRole(r)} className={`min-h-11 shrink-0 whitespace-nowrap rounded-full px-4 text-sm font-semibold ${role===r?'bg-brand-600 text-white':'text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800'}`}>{r}</button>)}</div><div id="role-panel" role="tabpanel" aria-labelledby={`tab-${role.replaceAll(' ','-')}`} tabIndex="0" className="m-1 mt-3 rounded-xl bg-brand-50 p-6 text-base font-semibold leading-7 text-slate-900 dark:bg-slate-900 dark:text-white"><School className="mb-3 text-brand-600"/>{roles[role]}</div></div></div></section>
    <section className="landing-section bg-[#07111f] py-24 text-white"><div className="landing-wrap grid gap-10 lg:grid-cols-[1fr_.8fr] lg:items-center"><Title dark eyebrow="Sinyal awal" title={<>Data mencatat apa yang terjadi.<br/>Gakuren membantu melihat apa yang berulang.</>} desc="Pola ketidakhadiran dan keterlambatan dapat menjadi sinyal agar sekolah melakukan peninjauan lebih awal."/><article className="rounded-3xl border border-amber-300/30 bg-gradient-to-br from-amber-400/10 to-brand-500/10 p-6"><span className="status-label !mt-0">Dalam Pengembangan</span><p className="mt-5 text-sm font-semibold text-amber-300">Perlu perhatian</p><h3 className="mt-2 text-xl font-bold">Siti Nurhaliza</h3><ul className="mt-4 space-y-2 text-sm text-slate-300"><li>3 kali izin mendadak dalam 14 hari</li><li>2 kali terlambat pada hari Senin</li></ul><div className="mt-5 border-t border-white/10 pt-4"><p className="text-xs text-slate-400">Rekomendasi</p><p className="mt-1 font-semibold">Tinjau bersama wali kelas</p></div></article></div></section>
    <section id="keamanan" className="landing-section bg-white py-24 dark:bg-slate-950"><div className="landing-wrap grid gap-10 lg:grid-cols-[1fr_.9fr]"><div><Title eyebrow="Keamanan dan integritas" title="Keputusan yang baik dimulai dari data yang dapat dipercaya." desc="Kontrol berlapis membantu sekolah menjaga keakuratan dan akuntabilitas data."/><ul className="mt-8 grid gap-3 sm:grid-cols-2">{security.map(x=><li key={x} className="flex items-center gap-3 text-sm font-semibold dark:text-white"><LockKeyhole size={17} className="shrink-0 text-brand-600"/>{x}</li>)}</ul></div><div className="self-center rounded-2xl border border-slate-200 bg-slate-50 p-5 dark:border-slate-700 dark:bg-slate-900"><p className="text-sm font-bold dark:text-white">Riwayat persetujuan</p>{[['07:12','Kehadiran dicatat','Selesai'],['07:14','Validasi perangkat','Selesai'],['07:18','Persetujuan wali kelas','Menunggu']].map(([time,label,status])=><div key={label} className="mt-4 grid grid-cols-[42px_1fr_auto] items-center gap-3 border-t border-slate-200 pt-4 text-xs dark:border-slate-700"><span className="text-slate-500">{time}</span><span className="font-semibold dark:text-white">{label}</span><span className={status==='Selesai'?'text-emerald-600':'text-amber-600'}>{status}</span></div>)}</div></div></section>
    <section className="landing-section bg-slate-50 py-24 dark:bg-slate-900"><div className="landing-wrap"><Title eyebrow="Laporan siap digunakan" title="Data yang siap digunakan, bukan sekadar disimpan." desc="Gakuren membantu operator menyiapkan rekap tanpa mengolah ulang data dari awal."/><div className="mt-10 grid gap-4 md:grid-cols-3">{reports.map(([group,items])=><article key={group} className="rounded-2xl bg-white p-5 dark:bg-slate-950"><h3 className="font-bold text-slate-950 dark:text-white">{group}</h3><ul className="mt-4 space-y-3">{items.map(item=><li key={item} className="flex gap-2 text-sm text-slate-600 dark:text-slate-300"><FileCheck2 size={16} className="mt-0.5 shrink-0 text-brand-600"/>{item}</li>)}</ul></article>)}</div><p className="mt-6 rounded-xl border border-brand-200 bg-brand-50 p-4 text-sm leading-6 text-brand-900 dark:border-brand-900 dark:bg-brand-900/20 dark:text-brand-100">Gakuren menyiapkan file untuk digunakan operator. Data tidak dikirim langsung ke Dapodik tanpa mekanisme dan izin resmi.</p></div></section>
  </>
}
