import { Fragment, useEffect, useRef, useState } from 'react'
import { Check, ChevronDown, X } from 'lucide-react'
import { comparisonGroups, FEATURE_STATUS, pricingPlans } from '../data/pricing'

function PlanCard({plan,onChoose}){
  const available=plan.features.filter(feature=>feature.status===FEATURE_STATUS.AVAILABLE).slice(0,7)
  const next=plan.features.filter(feature=>feature.status!==FEATURE_STATUS.AVAILABLE).slice(0,4)
  return <article className={`relative flex flex-col rounded-3xl border bg-white p-6 dark:bg-slate-950 ${plan.recommended?'border-brand-500 shadow-[0_18px_55px_-30px_rgba(33,150,243,.9)]':'border-slate-200 dark:border-slate-700'}`}>{plan.recommended&&<span className="absolute -top-3 left-6 rounded-full bg-brand-600 px-3 py-1 text-[10px] font-bold uppercase tracking-wide text-white">Direkomendasikan</span>}<p className="text-sm font-bold text-brand-700 dark:text-brand-200">{plan.name}</p><p className="mt-3 text-3xl font-bold tracking-tight text-slate-950 dark:text-white">{plan.priceLabel}</p><p className="mt-1 text-xs text-slate-500">{plan.billingPeriod}</p><p className="mt-4 font-semibold text-slate-900 dark:text-white">{plan.capacity}</p><div className="mt-5 border-y border-slate-200 py-3 text-sm dark:border-slate-700"><span className="text-slate-500">Biaya setup</span><strong className="float-right text-slate-900 dark:text-white">{plan.setupFee}</strong></div><ul className="mt-5 space-y-3">{available.map(feature=><li key={feature.name} className="flex gap-2 text-sm text-slate-700 dark:text-slate-200"><Check size={16} className="mt-0.5 shrink-0 text-emerald-600"/>{feature.name}</li>)}</ul>{next.length>0&&<div className="mt-5 rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-500">Fitur berikutnya dalam pengembangan</p><p className="mt-2 text-xs leading-5 text-slate-600 dark:text-slate-300">{next.map(item=>item.name).join(' • ')}</p></div>}<button type="button" onClick={()=>onChoose(plan)} className={`mt-6 min-h-11 w-full rounded-full px-5 text-sm font-bold ${plan.recommended?'bg-brand-600 text-white hover:bg-brand-700':'border border-slate-300 text-slate-900 hover:bg-slate-50 dark:border-slate-600 dark:text-white dark:hover:bg-slate-800'}`}>{plan.cta}</button></article>
}

function Comparison(){const[open,setOpen]=useState(false);return <div className="mt-9"><button type="button" aria-expanded={open} aria-controls="pricing-comparison" onClick={()=>setOpen(v=>!v)} className="mx-auto flex min-h-11 items-center gap-2 rounded-full border border-slate-300 px-5 text-sm font-bold text-slate-900 dark:border-slate-600 dark:text-white">Bandingkan Semua Fitur <ChevronDown size={17} className={open?'rotate-180':''}/></button>{open&&<div id="pricing-comparison" className="mt-6 overflow-x-auto rounded-2xl border border-slate-200 dark:border-slate-700"><table className="w-full min-w-[760px] bg-white text-left text-sm dark:bg-slate-950"><thead><tr><th className="p-4">Fitur</th>{pricingPlans.map(plan=><th key={plan.code} className="p-4 text-center">{plan.name}</th>)}</tr></thead><tbody>{comparisonGroups.map(group=><Fragment key={group.category}><tr className="bg-slate-50 dark:bg-slate-900"><th colSpan={5} className="px-4 py-2 text-xs uppercase tracking-wide text-brand-700 dark:text-brand-200">{group.category}</th></tr>{group.features.map(name=><tr key={name} className="border-t border-slate-100 dark:border-slate-800"><td className="p-4 text-slate-700 dark:text-slate-200">{name}</td>{pricingPlans.map(plan=>{const feature=plan.features.find(item=>item.name===name);return <td key={plan.code} className="p-3 text-center text-xs">{feature?.status||'—'}</td>})}</tr>)}</Fragment>)}</tbody></table></div>}</div>}

function InquiryDialog({plan,onClose}){const ref=useRef(null);const[sent,setSent]=useState(false);useEffect(()=>{ref.current?.focus();const close=e=>e.key==='Escape'&&onClose();document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[onClose]);return <div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/70 p-4" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div ref={ref} role="dialog" aria-modal="true" aria-labelledby="inquiry-title" tabIndex="-1" className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl dark:bg-slate-900"><div className="flex justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wide text-brand-600">Formulir konsultasi</p><h2 id="inquiry-title" className="mt-2 text-2xl font-bold dark:text-white">Paket {plan.name}</h2></div><button type="button" onClick={onClose} aria-label="Tutup formulir" className="grid h-11 w-11 place-items-center rounded-full"><X/></button></div>{sent?<p className="mt-6 rounded-xl bg-brand-50 p-5 text-sm leading-6 text-brand-900 dark:bg-brand-900/20 dark:text-brand-100">Permintaan tersimpan pada sesi ini. Kanal kontak resmi belum dikonfigurasi.</p>:<form className="mt-6 space-y-4" onSubmit={e=>{e.preventDefault();setSent(true)}}><label className="block text-sm font-semibold dark:text-white">Nama sekolah<input required minLength={2} maxLength={150} pattern="[A-Za-zÀ-ž0-9 .&'()-]+" title="Gunakan huruf, angka, spasi, dan tanda baca nama organisasi." autoComplete="organization" className="mt-2 min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 font-normal dark:border-slate-600"/></label><label className="block text-sm font-semibold dark:text-white">Nama kontak<input required minLength={2} maxLength={100} pattern="[A-Za-zÀ-ž .'-]+" title="Gunakan huruf dan tanda baca nama." autoComplete="name" className="mt-2 min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 font-normal dark:border-slate-600"/></label><label className="block text-sm font-semibold dark:text-white">Email atau nomor telepon<input required maxLength={254} pattern="(?:[^\\s@]+@[^\\s@]+\\.[^\\s@]{2,}|(?:\\+62|62|0)8[0-9]{7,12})" title="Masukkan email atau nomor telepon Indonesia yang valid." className="mt-2 min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 font-normal dark:border-slate-600"/></label><button className="min-h-11 w-full rounded-full bg-brand-600 px-5 font-bold text-white">Kirim permintaan konsultasi</button></form>}</div></div>}

export default function Pricing(){const[selected,setSelected]=useState(null);return <section id="harga" className="landing-section bg-white py-24 dark:bg-slate-950"><div className="landing-wrap"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-bold uppercase tracking-[.18em] text-brand-600 dark:text-brand-200">Rencana Paket Gakuren</p><h2 className="mt-4 text-3xl font-bold tracking-[-.03em] text-slate-950 dark:text-white sm:text-4xl">Paket yang mengikuti kebutuhan sekolah.</h2><p className="mt-4 leading-7 text-slate-600 dark:text-slate-300">Harga per sekolah per bulan, dengan kapasitas yang jelas dan biaya setup terpisah.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{pricingPlans.map(plan=><PlanCard key={plan.code} plan={plan} onChoose={setSelected}/>)}</div><Comparison/></div>{selected&&<InquiryDialog plan={selected} onClose={()=>setSelected(null)}/>}</section>}
