import { useEffect, useRef, useState } from 'react'
import { Check, ChevronDown, Info, Minus, X } from 'lucide-react'
import { comparisonGroups, FEATURE_STATUS, pricingFaqs, pricingPlans } from '../data/pricing'

const statusTone = {
  [FEATURE_STATUS.AVAILABLE]: 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-300',
  [FEATURE_STATUS.DEVELOPMENT]: 'bg-amber-50 text-amber-700 dark:bg-amber-950/50 dark:text-amber-300',
  [FEATURE_STATUS.CONTACT]: 'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300',
}

function Status({ value }) { return <span className={`rounded-full px-2 py-1 text-[9px] font-bold uppercase tracking-wide ${statusTone[value]}`}>{value}</span> }
function findFeature(plan, name) { return plan.features.find(feature => feature.name === name) }

function PlanCard({ plan, onChoose }) {
  return <article className={`relative flex h-full flex-col rounded-3xl border bg-white p-6 dark:bg-slate-950 ${plan.recommended ? 'border-brand-500 shadow-[0_18px_55px_-30px_rgba(33,150,243,.9)] lg:-translate-y-2' : 'border-slate-200 dark:border-slate-700'}`}>
    {plan.recommended && <span className="absolute -top-3 left-6 rounded-full bg-brand-600 px-3 py-1 text-[10px] font-bold uppercase tracking-wide text-white">Paling Direkomendasikan</span>}
    <p className="text-sm font-bold text-brand-700 dark:text-brand-200">{plan.name}</p>
    <p className="mt-4 text-3xl font-bold tracking-tight text-slate-950 dark:text-white">{plan.priceLabel}</p>
    <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">{plan.billingPeriod}</p>
    <p className="mt-5 font-semibold text-slate-900 dark:text-white">{plan.capacity}</p>
    <p className="mt-2 min-h-[72px] text-sm leading-6 text-slate-600 dark:text-slate-300">{plan.description}</p>
    <div className="mt-5 border-y border-slate-200 py-3 text-sm dark:border-slate-700"><span className="text-slate-500 dark:text-slate-400">Biaya setup</span><strong className="float-right text-slate-900 dark:text-white">{plan.setupFee}</strong></div>
    <ul className="mt-5 flex-1 space-y-3">{plan.features.map(feature => <li key={feature.name} className="grid grid-cols-[18px_1fr] gap-2 text-sm"><Check size={16} className="mt-0.5 text-brand-600"/><div><span className="text-slate-700 dark:text-slate-200">{feature.name}</span>{feature.note && <button type="button" title={feature.note} aria-label={`${feature.name}: ${feature.note}`} className="ml-1 inline-flex align-middle text-slate-400"><Info size={14}/></button>}<span className="mt-1.5 block"><Status value={feature.status}/></span></div></li>)}</ul>
    <button type="button" onClick={() => onChoose(plan)} className={`mt-7 w-full rounded-full px-5 py-3 text-sm font-bold ${plan.recommended ? 'bg-brand-600 text-white hover:bg-brand-700' : 'border border-slate-300 text-slate-900 hover:bg-slate-50 dark:border-slate-600 dark:text-white dark:hover:bg-slate-800'}`}>{plan.cta}</button>
  </article>
}

function Comparison() {
  const [open, setOpen] = useState(false)
  return <div className="mt-10"><button type="button" aria-expanded={open} aria-controls="pricing-comparison" onClick={() => setOpen(value => !value)} className="mx-auto flex items-center gap-2 rounded-full border border-slate-300 px-5 py-3 text-sm font-bold text-slate-900 dark:border-slate-600 dark:text-white">Bandingkan semua fitur <ChevronDown size={17} className={`transition-transform ${open ? 'rotate-180' : ''}`}/></button>{open && <div id="pricing-comparison" className="mt-6">
    <div className="hidden overflow-x-auto rounded-2xl border border-slate-200 dark:border-slate-700 md:block"><table className="w-full min-w-[850px] border-collapse bg-white text-left text-sm dark:bg-slate-950"><thead><tr><th className="p-4">Fitur</th>{pricingPlans.map(plan => <th key={plan.code} className="p-4 text-center">{plan.name}</th>)}</tr></thead><tbody>{comparisonGroups.map(group => <FragmentGroup key={group.category} group={group}/>)}</tbody></table></div>
    <div className="space-y-3 md:hidden">{pricingPlans.map(plan => <details key={plan.code} className="rounded-xl border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-950"><summary className="cursor-pointer font-bold dark:text-white">{plan.name}</summary><div className="mt-4 space-y-5">{comparisonGroups.map(group => <div key={group.category}><h4 className="text-xs font-bold uppercase tracking-wide text-brand-700 dark:text-brand-200">{group.category}</h4><ul className="mt-2 space-y-2">{group.features.map(name => {const feature=findFeature(plan,name);return <li key={name} className="flex items-start justify-between gap-3 text-sm text-slate-600 dark:text-slate-300"><span>{name}</span>{feature?<Status value={feature.status}/>:<Minus size={15}/>}</li>})}</ul></div>)}</div></details>)}</div>
  </div>}</div>
}

function FragmentGroup({ group }) { return <>{<tr className="bg-slate-50 dark:bg-slate-900"><th colSpan={5} className="px-4 py-2 text-xs uppercase tracking-wide text-brand-700 dark:text-brand-200">{group.category}</th></tr>}{group.features.map(name => <tr key={name} className="border-t border-slate-100 dark:border-slate-800"><td className="p-4 text-slate-700 dark:text-slate-200">{name}</td>{pricingPlans.map(plan => {const feature=findFeature(plan,name);return <td key={plan.code} className="p-3 text-center">{feature?<Status value={feature.status}/>:<Minus size={15} className="mx-auto text-slate-400"/>}</td>})}</tr>)}</> }

function InquiryDialog({ plan, onClose }) {
  const dialogRef = useRef(null); const [sent, setSent] = useState(false)
  useEffect(() => { dialogRef.current?.focus(); const close = event => event.key === 'Escape' && onClose(); document.addEventListener('keydown', close); return () => document.removeEventListener('keydown', close) }, [onClose])
  return <div role="presentation" className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/70 p-4" onMouseDown={event => event.target === event.currentTarget && onClose()}><div ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="inquiry-title" tabIndex="-1" className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl dark:bg-slate-900"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wide text-brand-600">Formulir konsultasi</p><h2 id="inquiry-title" className="mt-2 text-2xl font-bold text-slate-950 dark:text-white">Paket {plan.name}</h2></div><button type="button" onClick={onClose} aria-label="Tutup formulir" className="grid h-9 w-9 place-items-center rounded-full text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800"><X size={20}/></button></div>{sent?<div className="mt-6 rounded-xl bg-emerald-50 p-5 text-sm leading-6 text-emerald-800 dark:bg-emerald-950/50 dark:text-emerald-200">Permintaan tersimpan pada sesi ini. Kanal pengiriman kontak resmi belum dikonfigurasi; silakan lengkapi endpoint sebelum formulir digunakan di produksi.</div>:<form className="mt-6 space-y-4" onSubmit={event => {event.preventDefault();setSent(true)}}><label className="block text-sm font-semibold dark:text-white">Nama sekolah<input required name="school" autoComplete="organization" className="mt-2 w-full rounded-lg border border-slate-300 bg-transparent px-3 py-2.5 font-normal dark:border-slate-600"/></label><label className="block text-sm font-semibold dark:text-white">Nama kontak<input required name="name" autoComplete="name" className="mt-2 w-full rounded-lg border border-slate-300 bg-transparent px-3 py-2.5 font-normal dark:border-slate-600"/></label><label className="block text-sm font-semibold dark:text-white">Email atau nomor telepon<input required name="contact" className="mt-2 w-full rounded-lg border border-slate-300 bg-transparent px-3 py-2.5 font-normal dark:border-slate-600"/></label><button className="w-full rounded-full bg-brand-600 px-5 py-3 font-bold text-white hover:bg-brand-700">Kirim permintaan konsultasi</button><p className="text-xs leading-5 text-slate-500">Tidak ada pembayaran atau kartu kredit pada tahap ini.</p></form>}</div></div>
}

export default function Pricing() {
  const [selected, setSelected] = useState(null)
  return <section id="harga" className="landing-section bg-slate-50 py-24 dark:bg-slate-900"><div className="landing-wrap"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-bold uppercase tracking-[.18em] text-brand-600 dark:text-brand-200">Rencana Paket Gakuren</p><h2 className="mt-4 text-3xl font-bold tracking-[-.03em] text-slate-950 dark:text-white sm:text-4xl">Paket yang mengikuti kebutuhan sekolah.</h2><p className="mt-4 leading-7 text-slate-600 dark:text-slate-300">Mulai dari kebutuhan dasar kehadiran hingga pengelolaan beberapa sekolah dalam satu ekosistem.</p><p className="mt-3 text-sm font-semibold text-slate-900 dark:text-white">Harga per sekolah per bulan.</p></div><div className="mt-14 grid items-stretch gap-5 md:grid-cols-2 xl:grid-cols-4">{pricingPlans.map(plan => <PlanCard key={plan.code} plan={plan} onChoose={setSelected}/>)}</div><div className="mt-10 grid gap-4 rounded-2xl border border-slate-200 bg-white p-6 text-sm dark:border-slate-700 dark:bg-slate-950 sm:grid-cols-2"><div><strong className="block text-slate-950 dark:text-white">Butuh kapasitas tambahan?</strong><span className="mt-1 block text-slate-600 dark:text-slate-300">Tambahan 500 siswa tersedia mulai Rp75.000 per bulan.</span></div><div><strong className="block text-slate-950 dark:text-white">Tersedia uji coba gratis selama 30 hari.</strong><span className="mt-1 block text-slate-600 dark:text-slate-300">Tanpa permintaan kartu kredit pada formulir konsultasi.</span></div></div><p className="mt-4 text-center text-xs leading-5 text-slate-500">Harga dapat menyesuaikan kebutuhan implementasi, jumlah sekolah, kapasitas data, integrasi, dan layanan tambahan.</p><Comparison/><div className="mx-auto mt-20 max-w-3xl"><h2 className="text-center text-3xl font-bold tracking-tight text-slate-950 dark:text-white">Pertanyaan seputar harga</h2><div className="mt-8 divide-y divide-slate-200 border-y border-slate-200 dark:divide-slate-700 dark:border-slate-700">{pricingFaqs.map(([question,answer]) => <details key={question} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-bold text-slate-950 dark:text-white">{question}<ChevronDown size={18} className="shrink-0 transition-transform group-open:rotate-180"/></summary><p className="mt-3 pr-8 text-sm leading-6 text-slate-600 dark:text-slate-300">{answer}</p></details>)}</div></div></div>{selected&&<InquiryDialog plan={selected} onClose={() => setSelected(null)}/>}</section>
}
